name: Get Unity License
on: workflow_dispatch
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Request activation file
        id: activation
        uses: game-ci/unity-request-activation-file@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Manual-Activation-File
          path: ${{ steps.activation.outputs.filePath }}
