name: Desi Rush V1 Android APK

on:
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-DesiRush-V1-Android
          restore-keys: |
            Library-

      # Ye 2 line sabse important hai dirty error fix ke liye
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          allowDirtyBranch: true
          versioning: None
          customVersion: 1.0.0
          androidVersionCode: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DesiRush-V1-APK
          path: build/Android/*.apk
